import type { Metadata } from 'next'
import { playfair, atkinsonNext, atkinsonMono } from './fonts'
import '@/styles/globals.scss'
import { Providers } from './providers'
import { Header } from '@/components/layout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${playfair.variable} ${atkinsonNext.variable} ${atkinsonMono.variable}`}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
